server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xuhaixing/springCloudConfig.git
          search-paths: /oa
          default-label: master
        default-label: master
  profiles:
    active: dev
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://192.168.94.150:8761/eureka

---
spring:
  profiles: dev
logging:
  level:
    root: info

---
spring:
  profiles: test
logging:
  level:
    root: error